# Generated by Django 4.2.7 on 2025-02-04 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inserting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان تصویر')),
                ('file', models.ImageField(upload_to='images/', verbose_name='فایل تصویر')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده')),
            ],
        ),
    ]
