# Generated by Django 5.1.6 on 2025-03-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inserting', '0002_uploadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='fakeness',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='fakeness',
            field=models.FloatField(default=-1),
        ),
    ]
