# Generated by Django 5.1.6 on 2025-03-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inserting', '0003_uploadimage_fakeness_uploadvideo_fakeness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='fakeness',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='fakeness',
            field=models.IntegerField(default=-1),
        ),
    ]
